# Generated by Django 3.2.6 on 2021-08-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_site_last_ping_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='availability_status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='site',
            name='label',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='site',
            name='last_ping_date',
            field=models.DateTimeField(null=True, verbose_name='Дата последнего опроса'),
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.URLField(verbose_name='Адрес'),
        ),
    ]
