version: '3.9'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file: ./utils/.env
    depends_on:
      - redis

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  celery:
    build: ./backend
    command: celery -A config worker -l info
    volumes:
      - ./backend/:/usr/src/app/
    env_file: ./utils/.env
    depends_on:
      - redis

  celery-beat:
    build: ./backend
    command: celery -A config beat -l info
    volumes:
      - ./backend/:/usr/src/app/
    env_file: ./utils/.env
    depends_on:
      - redis